### PR TITLE
Fix in case DynamoDBMapper is already provided

### PR DESCRIPTION
**Pull request by gauravbrills**
Fix in case dynamoDbMapper is already provided,w e dont need to check for dynamodDbMapperCofig or the assert

references issue #91

### CODE REVIEW

**Comment by derjust** [comment]
Looking good. But as a burned kind def. want to add a unit test before merging. Will do that in the next days

**Comment by derjust** [comment]
Thanks for the PR!

**Comment by gauravbrills** [comment]
@derjust ya np .. was in a hurry couldn't add the test case using this custom implementation right now for my existing project .. will be great if you could merge the fix once approved in the 4.5.x branch as well .

**Comment by derjust** [comment]
Merged in branch `issue_91` to add unit test.
Thanks for the PR!

**Comment by gauravbrills** [comment]
HI @derjust  one more thing I guess needs to be changed is getOverriddenTableName whcih will give NPE if dynamoDbconfig is not provided . Can we make the method below Public rather than introducing the new method we have for the mapper as config could be required **getOverriddenTableName**
`DynamoDBTemplate(AmazonDynamoDB amazonDynamoDB, DynamoDBMapperConfig dynamoDBMapperConfig,
         DynamoDBMapper dynamoDBMapper)
`

**Comment by derjust** [comment]
absolutely doable. Any chance to get access to your (maybe simplified) complete scenario to add it as a knot test?

**Comment by gauravbrills** [comment]
Hi in my case I am adding a DynamoDbTemplate with a configured encryption transformer as below .. Currently using a custom DynamodBTemplate class .

`return new DynamoDBTemplate(amazonDynamoDB, this.dynamoDBMapperConfig(), new DynamoDBMapper(amazonDynamoDB,
            this.dynamoDBMapperConfig(), new AttributeEncryptor(new DirectKmsMaterialProvider(awsKMS, kmsKey))));
`

**Comment by derjust** [comment]
Created #108 to go on with the discussion there/have an issue ID to relate to

**Pull request merged**
